title: "Green Worm"
subtitle: "W3C Standards based Web Development and Design"
author:
  name: Ash McKenzie
  uri: http://greenworm.com.au
  email: ash@greenworm.com.au
theme: greenworm
cache: false
content: content
production:
  cache: true    
  content: /home/apps/greenworm/current/content
  google_analytics_code: "UA-8842201-1"